version: "3.7"

services:
  es01:
    image: elasticsearch:7.9.0
    container_name: es01
    ports:
      - 9200:9200
    volumes:
        - $HOME/dev/data/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
      - data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: kibana:7.9.0
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - es01:elasticsearch
    volumes:
      - $HOME/dev/data/kibana/data:/usr/share/kibana/data
    environment:
      - DATA_PATH=/usr/share/kibana/data
      - JAVA_OPTS=-Xms1024m -Xmx1024m
    networks:
      - data


  minio:
    image: minio/minio
    container_name: minio
    command: "server /data"
    ports:
      - 9000:9000
    volumes:
      - $HOME/dev/data/minio/data:/data
    networks:
      - data
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

networks:
  data: {}
